### ISSUE TITLE
NuGet release?

### ISSUE THREAD

**Issue by Xwilarg** [darkfrostystorm/NotificationTrayIconSharp#10]
Hey,

Any plan to release this on nuget.org?

**Comment by darkfrostystorm** [comment]
@Xwilarg https://www.nuget.org/packages/NotificationIconSharp/

**Comment by darkfrostystorm** [comment]
On an aside note, I will give this more love once the project I am working on I wrote it for originally releases at work :-) fix the nuget package details etc.  I am also moving, time is tight :-(

**Comment by Xwilarg** [comment]
> 
> 
> On an aside note, I will give this more love once the project I am working on I wrote it for originally releases at work :-) fix the nuget package details etc. I am also moving, time is tight :-(

Sure take your time, your work helped me a lot so thanks for that already!



> 
> 
> @Xwilarg https://www.nuget.org/packages/NotificationIconSharp/

Amazing, I don't know if it's indended but the NuGet doesn't have the same name as the Github repository (that's why I didn't find it)
