### ISSUE TITLE
Demo Runs Very High CPU Load

### ISSUE THREAD

**Issue by seanocali** [darkfrostystorm/NotificationTrayIconSharp#6]
Just tried it in Windows, showing around 20-25% CPU load.

**Comment by darkfrostystorm** [comment]
That's fine, it's not really an issue for a demo, it's a while loop calling win32 PeekMsg, there is no no-op so nothing is preventing the while loop from just spinning as fast as possible.

In the Demo you can change trayIcon?.DoMessageLoop(false); to trayIcon?.DoMessageLoop(true); and the call will use win32 GetMessage, which is a no-op wait.

If you are using this in Avalonia, you do not need to call DoMessageLoop at all, luckily, as Avalonia is already running a message loop for you!

**Comment by darkfrostystorm** [comment]
`using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Markup.Xaml;
using Avalonia.Threading;
using MonoMac.AppKit;
using MonoMac.Foundation;
using NotificationIconSharp;
using System.ComponentModel;
using System.Runtime.InteropServices;
using Tdvx.Updater.HelperCore.Views;

namespace Tdvx.Updater.HelperCore
{
    public class App2 : Application
    {
        private MainWindowView _mainWindow = null;
        private NotificationIcon _notificationIcon = null;

        public override void Initialize()
        {
            AvaloniaXamlLoader.Load(this);
        }

        public override void OnFrameworkInitializationCompleted()
        {
            /// Handle Initializing the NSApplication and setting an appropriate
            /// app delegate override for the app.  This currently uses Avalonia's
            /// MonoMac.NetStandard fork from the old Mono framework, this can be
            /// moved to Native if we ever have issues, but these APIs haven't
            /// changed in 13 years based on monos checkins
            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                NSApplication.Init();
                NSApplication.SharedApplication.Delegate = new OSXAppDelegate();
            }
            if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
            {

                desktop.MainWindow = new MainWindowView();
            }
            base.OnFrameworkInitializationCompleted();
            if (_notificationIcon == null)
            {
                // Create the notification tray icon, this should be the main thread anyways
                _notificationIcon = new NotificationIcon("path to icon.png/ico");
                _notificationIcon.NotificationIconSelected += Icon_NotificationIconSelected;
            }
        }

        /// <summary>
        /// show and/or create the main window instance if necessary
        /// </summary>
        public void RestoreMainWindow()
        {
            var desktopApplicationLifetime = Current.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (_mainWindow == null)
            {
                _mainWindow = new MainWindowView();
                _mainWindow.Closing += MainWindow_Closing;
            }
            if (desktopApplicationLifetime?.MainWindow != _mainWindow)
            {
                desktopApplicationLifetime.MainWindow = _mainWindow;
            }
            _mainWindow.Show();
            _mainWindow.WindowState = WindowState.Normal;
            _mainWindow.BringIntoView();
            _mainWindow.Focus();
            ShowApplicationInstance();
        }

        /// <summary>
        /// Exit the application
        /// </summary>
        public void Exit()
        {
            (Current.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime).Shutdown(0);
        }

        /// <summary>
        /// OSX Helper function used to Hide the dock icon when running as a daemon
        /// </summary>
        public static void HideApplicationInstance()
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                NSApplication.SharedApplication.ActivationPolicy = NSApplicationActivationPolicy.Accessory;
            }
        }

        /// <summary>
        /// OSX Helper function used to Show the dock icon when running as a daemon
        /// </summary>
        public static void ShowApplicationInstance()
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                NSApplication.SharedApplication.ActivationPolicy = NSApplicationActivationPolicy.Regular;
            }
        }

        private void MainWindow_Closing(object sender, CancelEventArgs e)
        {
            _mainWindow?.Hide();
            _mainWindow = null;
            HideApplicationInstance();
        }

        private void Icon_NotificationIconSelected(NotificationIcon icon)
        {
            Dispatcher.UIThread.Post(() =>
            {
                RestoreMainWindow(); // Restore main window on notification icon click
            });
        }
    }

    /// <summary>
    /// OSX Helper class, overrides Avalonias default AppDelegate to give us more
    /// control over a few pieces of behavior allowing us to get away with some
    /// stuff in a system daemon that the Avalonia devs didn't anticipate ;-)
    /// </summary>
    public class OSXAppDelegate : NSApplicationDelegate
    {
        public OSXAppDelegate()
        {
            AvaloniaLocator.CurrentMutable.Bind<OSXAppDelegate>().ToConstant(this);
        }

        /// <summary>
        /// Because we are creating our own mac application delegate we are removing / overriding 
        /// the one that Avalonia creates. This causes the application to not be handled as it should.
        /// This is the Avalonia Implementation: https://github.com/AvaloniaUI/Avalonia/blob/5a2ef35dacbce0438b66d9f012e5f629045beb3d/native/Avalonia.Native/src/OSX/app.mm
        /// So what we are doing here is re-creating this implementation to mimick their behavior.
        /// </summary>
        /// <param name="notification"></param>
        public override void WillFinishLaunching(NSNotification notification)
        {
            if (NSApplication.SharedApplication.ActivationPolicy != NSApplicationActivationPolicy.Regular)
            {
                foreach (var x in NSRunningApplication.GetRunningApplications(@"com.apple.dock"))
                {
                    x.Activate(NSApplicationActivationOptions.ActivateIgnoringOtherWindows);
                    break;
                }

                NSApplication.SharedApplication.ActivationPolicy = NSApplicationActivationPolicy.Accessory;
            }
        }

        /// <summary>
        /// Because we are creating our own mac application delegate we are removing / overriding 
        /// the one that Avalonia creates. This causes the application to not be handled as it should.
        /// This is the Avalonia Implementation: https://github.com/AvaloniaUI/Avalonia/blob/5a2ef35dacbce0438b66d9f012e5f629045beb3d/native/Avalonia.Native/src/OSX/app.mm
        /// So what we are doing here is re-creating this implementation to mimick their behavior.
        /// </summary>
        /// <param name="notification"></param>
        public override void DidFinishLaunching(NSNotification notification)
        {
            NSRunningApplication.CurrentApplication.Activate(NSApplicationActivationOptions.ActivateIgnoringOtherWindows);
        }
    }`

**Comment by darkfrostystorm** [comment]
There's some Demo Code attached for an avalonia app, to run it as a Windows Run on Login application, and as an OSX LaunchAgent


If you are running as a LaunchAgent you need the OSXAppDelegate and MonoMac NetStandard nuget (by the avalonia team), this keeps the icon for the avalonia app from always being in the OSX dock.

As you'll notice, there's no need for the message pumping that's eating the CPU for you :D

**Comment by darkfrostystorm** [comment]
@seanocali I flipped the wait flag for the runloop in the demo app, you should see less CPU useage.
